
    create table arrende_arrendator (
        pk_id bigint not null auto_increment,
        relaterad_fr_o_m_datum datetime(6),
        relaterad_t_o_m_datum datetime(6),
        arrendekontrakt varchar(255),
        avdelning varchar(255),
        betalarnummer_kontakt varchar(255),
        betalarnummerlangd_kontakt varchar(255),
        clearingnummer_kontakt varchar(255),
        e_post varchar(255),
        efakturaadress varchar(255),
        efternamn varchar(255),
        foredraget_kontaktsatt varchar(255),
        fornamn varchar(255),
        id varchar(255),
        kategori varchar(255),
        kontaktid varchar(255),
        konto_kontakt varchar(255),
        kontraktsrelation varchar(255),
        land varchar(255),
        namn varchar(255),
        ordning varchar(255),
        ort varchar(255),
        person_org_nr varchar(255),
        postadress varchar(255),
        postadress2 varchar(255),
        postnummer varchar(255),
        svefaktura varchar(255),
        telefon_arbete varchar(255),
        telefon_hem varchar(255),
        telefon_mobil varchar(255),
        primary key (pk_id)
    ) engine=InnoDB;

    create table arrende_arrendeartikel (
        pk_id bigint not null auto_increment,
        aktiv varchar(255),
        arrendeartikel varchar(255),
        artikelbenamning varchar(255),
        artikelgrupp varchar(255),
        artikeltyp varchar(255),
        avdrag varchar(255),
        avitext varchar(255),
        avvikelsetolerans_procent varchar(255),
        debiteras_alltid_hel_period varchar(255),
        id varchar(255),
        ingar_i_kontraktssumma varchar(255),
        pris varchar(255),
        reglering varchar(255),
        summarad varchar(255),
        primary key (pk_id)
    ) engine=InnoDB;

    create table arrende_arrendekontrakt (
        fr_o_m_datum datetime(6),
        godkant_datum datetime(6),
        kontraktsdatum datetime(6),
        onskad_avflyttning datetime(6),
        pk_id bigint not null auto_increment,
        preliminart_uppsagt_datum datetime(6),
        sista_debiteringsdatum datetime(6),
        t_o_m_datum datetime(6),
        uppsagt_datum datetime(6),
        arrendekontrakt varchar(255),
        debiteringstyp varchar(255),
        enhet_forlangning varchar(255),
        enhet_upps_tid_arrendator varchar(255),
        enhet_upps_tid_hyresvard varchar(255),
        fakturaperiod varchar(255),
        forlangning varchar(255),
        frifalt varchar(255),
        huvudkontrakt varchar(255),
        hyresid varchar(255),
        id varchar(255),
        kontraktsarea varchar(255),
        kontraktsnamn varchar(255),
        kontraktstyp varchar(255),
        kopplat_till_id varchar(255),
        markning varchar(255),
        upps_tid_arrendator varchar(255),
        upps_tid_hyresvard varchar(255),
        uppsagt_av varchar(255),
        primary key (pk_id)
    ) engine=InnoDB;

    create table arrende_arrendekontraktsrader (
        debiteras_fr_o_m_datum datetime(6),
        debiteras_t_o_m_datum datetime(6),
        del_av_ar_fr_o_m datetime(6),
        del_av_ar_t_o_m datetime(6),
        pk_id bigint not null auto_increment,
        arrendeartikel varchar(255),
        arrendekontrakt varchar(255),
        arshyra varchar(255),
        avitext varchar(255),
        basarshyra varchar(255),
        id varchar(255),
        index_nuvarande_ar varchar(255),
        index_nuvarande_manad varchar(255),
        index_nuvarande_varde varchar(255),
        indexandel varchar(255),
        indexbasar varchar(255),
        indexbasmanad varchar(255),
        indexbasvarde varchar(255),
        indexklausul varchar(255),
        indexnamn varchar(255),
        radnummer varchar(255),
        primary key (pk_id)
    ) engine=InnoDB;

    create table fastighetsbas_fastighet (
        fangesdatum datetime(6),
        pk_id bigint not null auto_increment,
        agare varchar(255),
        agarenamn varchar(255),
        agarforhallande varchar(255),
        block varchar(255),
        en_forvaltningsenhet_kopplad varchar(255),
        fastighetsbeteckning varchar(255),
        fastighetsnr varchar(255),
        foretag varchar(255),
        foretagsnamn varchar(255),
        fran_datum varchar(255),
        hyresid varchar(255),
        id varchar(255),
        kommun varchar(255),
        land varchar(255),
        ort varchar(255),
        postadress varchar(255),
        postadress2 varchar(255),
        postnummer varchar(255),
        till_datum varchar(255),
        tomtratt varchar(255),
        tomtratt_dodad_datum varchar(255),
        trakt varchar(255),
        primary key (pk_id)
    ) engine=InnoDB;

    create table gemensamt_notering (
        pk_id bigint not null auto_increment,
        arrendeobjekt varchar(255),
        bilplats varchar(255),
        bostad varchar(255),
        byggnad varchar(255),
        byggnadsdel varchar(255),
        fastighetsnr varchar(255),
        filnamn varchar(255),
        folder varchar(255),
        foretag varchar(255),
        forvaltningsenhet varchar(255),
        id varchar(255),
        komponent varchar(255),
        lokal varchar(255),
        markyta varchar(255),
        noteringsid varchar(255),
        noteringsnamn varchar(255),
        objektid varchar(255),
        objektid2 varchar(255),
        ovrigt_hyresobjekt varchar(255),
        prioritet varchar(255),
        rum varchar(255),
        system varchar(255),
        typ varchar(255),
        underhallsenhet varchar(255),
        uppgang_vaning varchar(255),
        primary key (pk_id)
    ) engine=InnoDB;

    create table kundreskontra_kund (
        pk_id bigint not null auto_increment,
        aktiv varchar(255),
        avdelning varchar(255),
        e_post varchar(255),
        efakturaadress varchar(255),
        efternamn varchar(255),
        foredraget_kontaktsatt varchar(255),
        fornamn varchar(255),
        forvaltartyp varchar(255),
        god_man_forvaltare varchar(255),
        id varchar(255),
        kategori varchar(255),
        kontaktid varchar(255),
        land varchar(255),
        namn varchar(255),
        ort varchar(255),
        person_org_nr varchar(255),
        postadress varchar(255),
        postadress2 varchar(255),
        postnummer varchar(255),
        svefaktura varchar(255),
        telefon_arbete varchar(255),
        telefon_hem varchar(255),
        telefon_mobil varchar(255),
        primary key (pk_id)
    ) engine=InnoDB;
